from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any


def _copy_if_exists(source: Path, target: Path) -> None:
    if source.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def export_paper_bundle(run_dir: Path, output_dir: Path) -> dict[str, Any]:
    manifest_path = run_dir / "manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(manifest_path)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    output_dir.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []
    for relative in ["project_report.md", "manifest.json", "project_snapshot.yaml", "replay_project.yaml"]:
        source = run_dir / relative
        target = output_dir / "source" / relative
        if source.exists():
            _copy_if_exists(source, target)
            copied.append(str(target.relative_to(output_dir)))

    for folder in ("claims", "analyses", "figures", "provenance"):
        source = run_dir / folder
        target = output_dir / folder
        if source.exists():
            shutil.copytree(source, target, dirs_exist_ok=True)
            copied.extend(str(path.relative_to(output_dir)) for path in target.rglob("*") if path.is_file())

    methods_lines = [
        "# Methods Export",
        "",
        f"Project: **{manifest['project']['title']}**",
        "",
        "This bundle was generated by FELRA from a finite-budget computational run.",
        "",
        "## Environment",
        "",
    ]
    for key, value in (manifest.get("environment") or {}).items():
        methods_lines.append(f"- `{key}`: `{value}`")
    methods_lines.extend(["", "## Data and analyses", ""])
    for dataset in manifest.get("datasets", []):
        methods_lines.append(
            f"- Dataset `{dataset['id']}`: {dataset['rows']} normalized rows; source hash `{dataset['source_sha256']}`."
        )
    for analysis in manifest.get("analyses", []):
        methods_lines.append(
            f"- Analysis `{analysis['id']}` (`{analysis['type']}`), success: `{analysis['success']}`."
        )
    (output_dir / "METHODS.md").write_text("\n".join(methods_lines) + "\n", encoding="utf-8")

    results_lines = [
        "# Results Export",
        "",
        f"Overall run status: **{'PASS' if manifest.get('passed') else 'ATTENTION REQUIRED'}**",
        "",
        f"Result fingerprint: `{manifest.get('result_sha256')}`",
        "",
        "## Claims",
        "",
    ]
    for claim in manifest.get("claims", []):
        results_lines.append(f"- `{claim['id']}`: `{'PASS' if claim['passed'] else 'FAIL'}`")
    results_lines.extend(["", "## Analyses", ""])
    for analysis in manifest.get("analyses", []):
        results_lines.append(f"- `{analysis['id']}`: `{'PASS' if analysis['success'] else 'FAIL'}`")
    (output_dir / "RESULTS.md").write_text("\n".join(results_lines) + "\n", encoding="utf-8")

    limitations = """# Limitations\n\n- FELRA outputs are finite-budget computational evidence, not universal mathematical proof.\n- Statistical results depend on the declared data, assumptions, model choices, and analysis plan.\n- Reuse of the same data for model selection and performance reporting may produce optimistic estimates.\n- Synthetic demonstration data must not be represented as external empirical evidence.\n- Preregistration matching shows plan consistency, not scientific validity.\n"""
    (output_dir / "LIMITATIONS.md").write_text(limitations, encoding="utf-8")

    citation = f"""cff-version: 1.2.0\nmessage: \"If you use this FELRA evidence bundle, cite the project and software version.\"\ntitle: \"{manifest['project']['title']} — FELRA evidence bundle\"\ntype: dataset\nauthors:\n  - family-names: \"Neo.K\"\nversion: \"{manifest.get('environment', {}).get('felra', 'unknown')}\"\nrepository-code: \"https://github.com/kakon77777-commits/FELRA\"\n"""
    (output_dir / "CITATION.cff").write_text(citation, encoding="utf-8")

    file_index = []
    for path in sorted(output_dir.rglob("*")):
        if path.is_file() and path.name != "EXPORT_MANIFEST.json":
            file_index.append(
                {
                    "path": str(path.relative_to(output_dir)),
                    "size": path.stat().st_size,
                    "sha256": _sha256(path),
                }
            )
    export_manifest = {
        "schema_version": "1.0",
        "source_run": run_dir.name,
        "project": manifest["project"],
        "result_sha256": manifest.get("result_sha256"),
        "files": file_index,
    }
    (output_dir / "EXPORT_MANIFEST.json").write_text(
        json.dumps(export_manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    return export_manifest
